// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnXaObU-uocXCmZjk3mP45DQG0BgpbJU0',
    appId: '1:628255971234:web:d457d84371dafb7ad244fb',
    messagingSenderId: '628255971234',
    projectId: 'proyek-akhir-9c8f8',
    authDomain: 'proyek-akhir-9c8f8.firebaseapp.com',
    storageBucket: 'proyek-akhir-9c8f8.appspot.com',
    measurementId: 'G-XWV6KJ5JC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh4B0vWzW3xAnD-D3QbUHFrEU9sBf_iJA',
    appId: '1:628255971234:android:0709ac130b8c7384d244fb',
    messagingSenderId: '628255971234',
    projectId: 'proyek-akhir-9c8f8',
    storageBucket: 'proyek-akhir-9c8f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdPnbSdyhTxRqTMiSIwfGmyI25MPUlMdc',
    appId: '1:628255971234:ios:8bd92df8b8872f85d244fb',
    messagingSenderId: '628255971234',
    projectId: 'proyek-akhir-9c8f8',
    storageBucket: 'proyek-akhir-9c8f8.appspot.com',
    iosBundleId: 'com.example.tugasAkhir',
  );
}
